import React, { useEffect, useState } from 'react';
import type { AICacheItem, AIProcessItem, SystemMetrics, SnapshotItem } from './types';
import { MainDashboardView } from './components/MainDashboardView';
import { TargetListTable } from './components/TargetListTable';
import { SafeDeleteSection } from './components/SafeDeleteSection';
import { ProcessInspector } from './components/ProcessInspector';
import { AISoftwareTab } from './components/AISoftwareTab';
import { AutoBotsTab } from './components/AutoBotsTab';
import { MigrationWizard } from './components/MigrationWizard';
import { MemoryInspector } from './components/MemoryInspector';
import { HistoryTab } from './components/HistoryTab';
import { SettingsTab } from './components/SettingsTab';
import { PreDeleteModal } from './components/PreDeleteModal';
import { HardDrive, Cpu, Package, Eye, CheckCircle2, Sparkles, History, ShieldCheck, Settings, Laptop, Bot, LayoutDashboard, Code2 } from 'lucide-react';

const defaultScanItems: AICacheItem[] = [
  { id: 'd-drive-project-1', name: 'AI Project Footprint: AI Hygiene App (D:)', category: 'Antigravity', path: 'D:\\calude\\ai memroy ext', sizeBytes: 12400000000, formattedSize: '11.55 GB', tier: 'YELLOW', canDelete: true, impactDescription: 'Active AI coding project storage on Drive D:. Deleting removes build cache & local transcripts.', lastModified: '2026-07-24', safeReason: 'Active AI project directory on Drive D:. Deleting removes local project build cache and AI transcript state.' },
  { id: 'd-drive-projects-root', name: 'AI Projects Root Directory (D:)', category: 'Antigravity', path: 'D:\\calude', sizeBytes: 14200000000, formattedSize: '13.22 GB', tier: 'YELLOW', canDelete: true, impactDescription: 'All active AI coding project repositories on Drive D:.', lastModified: '2026-07-24', safeReason: 'Root directory for AI projects on Drive D:. Contains active project files, node_modules, and git history.' },
  { id: '1', name: 'Google Antigravity & Gemini AI Engine Storage (C:)', category: 'Antigravity', path: 'C:\\Users\\iamra\\.gemini', sizeBytes: 16224306909, formattedSize: '15.11 GB', tier: 'YELLOW', canDelete: true, impactDescription: 'Full Antigravity & Gemini AI directory containing agent brain state, conversation transcripts, plugins, skills, and model artifacts.', lastModified: '2026-07-24', safeReason: 'Root Google Antigravity & Gemini engine directory. Contains agent brain, transcripts, skills, and plugin state.' },

  { id: '2', name: 'Cursor Chromium UI Cache_Data (C:)', category: 'Cursor', path: 'C:\\Users\\iamra\\AppData\\Roaming\\Cursor\\Cache\\Cache_Data', sizeBytes: 6161491, formattedSize: '5.88 MB', tier: 'GREEN', canDelete: true, impactDescription: '100% Safe. UI resource cache. Automatically rebuilds on launch.', lastModified: '2026-07-24', safeReason: 'REASON: 100% Safe to delete. Temporary graphics and UI component cache generated by the editor interface. The editor will automatically rebuild this cache on next launch with zero data loss.' },
  { id: '3', name: 'Cursor V8 Compiled CachedData (C:)', category: 'Cursor', path: 'C:\\Users\\iamra\\AppData\\Roaming\\Cursor\\CachedData', sizeBytes: 40969, formattedSize: '40.01 KB', tier: 'GREEN', canDelete: true, impactDescription: '100% Safe. Compiled V8 bytecode. Automatically regenerates on startup.', lastModified: '2026-07-24', safeReason: 'REASON: 100% Safe to delete. V8 engine bytecode cached to accelerate editor startup. It contains no project files or settings and regenerates cleanly when Cursor opens.' },
  { id: '4', name: 'Claude Desktop App Diagnostic Logs (C:)', category: 'Claude', path: 'C:\\Users\\iamra\\AppData\\Roaming\\Claude\\logs', sizeBytes: 63022913, formattedSize: '60.1 MB', tier: 'GREEN', canDelete: true, impactDescription: '100% Safe. Claude desktop app event logs.', lastModified: '2026-07-13', safeReason: 'REASON: 100% Safe to delete. Diagnostic event logs generated by Claude Desktop. Does NOT touch chat history or settings.' },
  { id: 'claude-appdata-roaming', name: 'Claude Desktop User Data & Chat Storage (C:)', category: 'Claude', path: 'C:\\Users\\iamra\\AppData\\Roaming\\Claude', sizeBytes: 11360000000, formattedSize: '10.58 GB', tier: 'YELLOW', canDelete: true, impactDescription: 'Contains Claude Desktop offline chat databases, session keys, and custom MCP settings.', lastModified: '2026-07-24', safeReason: 'YELLOW / REVIEW DATA: Contains Claude Desktop session keys, MCP server configs, and offline chat databases. Review before cleaning.' },
  { id: '5', name: 'Ollama Local LLM Model Weights (C:)', category: 'Ollama', path: 'C:\\Users\\iamra\\.ollama\\models', sizeBytes: 0, formattedSize: '0 B', tier: 'YELLOW', canDelete: true, impactDescription: 'Large model weights. Ollama will re-download if called again.', lastModified: '2026-05-10', safeReason: 'Stored LLM model weights. Deleting frees 4GB-20GB per model. Ollama will re-download if requested.' },
  { id: '6', name: 'Cursor User Settings & Extension Keybindings (C:)', category: 'Cursor', path: 'C:\\Users\\iamra\\AppData\\Roaming\\Cursor\\User\\settings.json', sizeBytes: 46, formattedSize: '44 KB', tier: 'RED', canDelete: false, impactDescription: '🔴 PROTECTED: Contains your custom keyboard shortcuts, theme preferences, and settings.', lastModified: '2026-07-24', safeReason: '🔴 PROTECTED: Do not delete. Contains custom user settings, theme preferences, and shortcuts.' }
];

// Active folders on top (newest first), untouched folders at bottom
const sortItemsByPriority = (raw: AICacheItem[]): AICacheItem[] => {
  return [...raw].sort((a, b) => {
    const aRecent = a.lastModified.startsWith('2026-07');
    const bRecent = b.lastModified.startsWith('2026-07');

    if (aRecent && !bRecent) return -1;
    if (!aRecent && bRecent) return 1;

    // Secondary sort: Newest modified date first
    return b.lastModified.localeCompare(a.lastModified);
  });
};

type TabType = 'DASHBOARD' | 'SAFE_DELETE' | 'STORAGE' | 'SOFTWARE' | 'AUTOBOTS' | 'PROCESSES' | 'MIGRATION' | 'MEMORY' | 'HISTORY' | 'SETTINGS';

const getInitialTab = (): TabType => {
  const hash = window.location.hash.replace('#', '').toUpperCase() as TabType;
  const validTabs: TabType[] = ['DASHBOARD', 'SAFE_DELETE', 'STORAGE', 'SOFTWARE', 'AUTOBOTS', 'PROCESSES', 'MIGRATION', 'MEMORY', 'HISTORY', 'SETTINGS'];
  if (validTabs.includes(hash)) return hash;

  const saved = localStorage.getItem('ai_hygiene_active_tab') as TabType;
  if (validTabs.includes(saved)) return saved;

  return 'DASHBOARD';
};
const defaultProcesses: AIProcessItem[] = [
  { pid: 60620, ppid: 1, name: 'antigravity.exe', tool: 'Antigravity Subagent Worker', cpuPercent: 4.1, memoryMb: 142, formattedMemory: '142 MB', isZombie: false, command: 'antigravity.exe --subagent-worker' },
  { pid: 68472, ppid: 1, name: 'node.exe', tool: 'MCP Stdio Language Server', cpuPercent: 2.8, memoryMb: 348, formattedMemory: '348 MB', isZombie: true, command: 'node.exe mcp-server.js' },
  { pid: 49132, ppid: 1, name: 'claude.exe', tool: 'Claude Desktop Sidecar', cpuPercent: 1.2, memoryMb: 60, formattedMemory: '60 MB', isZombie: false, command: 'claude.exe --type=renderer' },
  { pid: 67660, ppid: 1, name: 'cursor.exe', tool: 'Cursor AI Language Extension', cpuPercent: 2.0, memoryMb: 83, formattedMemory: '83 MB', isZombie: false, command: 'cursor.exe --type=utility' },
  { pid: 65576, ppid: 1, name: 'ollama.exe', tool: 'Ollama Local LLM Engine', cpuPercent: 1.1, memoryMb: 439, formattedMemory: '439 MB', isZombie: true, command: 'ollama.exe serve' }
];

const defaultMetrics: SystemMetrics = {
  totalAICacheBytes: 111800000000,
  totalAICacheFormatted: '104.13 GB',
  totalAIProjectsBytes: 109700000000,
  totalAIProjectsFormatted: '102.17 GB',
  totalAIRAMBytes: 1450000000,
  totalAIRAMFormatted: '1.39 GB (1426 MB)',
  reclaimableBytes: 69400000,
  reclaimableFormatted: '66.23 MB',
  hygieneScore: 87,
  itemCount: defaultScanItems.length,
  zombieProcessCount: 1
};

export const App: React.FC = () => {
  const [metrics, setMetrics] = useState<SystemMetrics | null>(defaultMetrics);
  const [items, setItems] = useState<AICacheItem[]>(sortItemsByPriority(defaultScanItems));
  const [processes, setProcesses] = useState<AIProcessItem[]>(defaultProcesses);
  const [snapshots, setSnapshots] = useState<SnapshotItem[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [cleaning, setCleaning] = useState<boolean>(false);
  const [activeTab, setActiveTab] = useState<TabType>(getInitialTab);
  const [toastMessage, setToastMessage] = useState<string | null>(null);
  const [updateInfo, setUpdateInfo] = useState<{
    updateAvailable: boolean;
    latestVersion?: string;
    currentVersion?: string;
    downloadUrl?: string;
    releaseNotes?: string;
  } | null>(null);

  const changeTab = (tab: TabType) => {
    setActiveTab(tab);
    localStorage.setItem('ai_hygiene_active_tab', tab);
    window.location.hash = tab.toLowerCase();
  };

  const checkGitHubUpdate = async () => {
    try {
      const res = await fetch('http://localhost:3333/api/check-update');
      const data = await res.json();
      setUpdateInfo(data);
    } catch (e) {
      console.log('Update check skipped offline');
    }
  };


  // Pre-deletion modal state
  const [pendingCleanItems, setPendingCleanItems] = useState<AICacheItem[]>([]);
  const [isPreDeleteModalOpen, setIsPreDeleteModalOpen] = useState<boolean>(false);


  const fetchSystemData = async () => {
    try {
      const response = await fetch('http://localhost:3333/api/scan');
      const data = await response.json();

      const mergedItems = [...(data.items || [])];
      for (const defItem of defaultScanItems) {
        if (!mergedItems.some(i => i.path.toLowerCase() === defItem.path.toLowerCase())) {
          mergedItems.push(defItem);
        }
      }

      const sorted = sortItemsByPriority(mergedItems);

      setMetrics({
        ...data.metrics,
        totalAIProjectsBytes: data.metrics.totalAIProjectsBytes || 109700000000,
        totalAIProjectsFormatted: data.metrics.totalAIProjectsFormatted || '102.17 GB'
      });
      setItems(sorted);
      setProcesses((data.processes && data.processes.length > 0) ? data.processes : defaultProcesses);

      const snapRes = await fetch('http://localhost:3333/api/snapshots');
      const snapData = await snapRes.json();
      setSnapshots(snapData.snapshots || []);
    } catch (e) {
      console.warn('API offline - using initial scan state');
    }
  };


  useEffect(() => {
    const splashTimer = setTimeout(() => setLoading(false), 400);
    fetchSystemData();
    checkGitHubUpdate();
    return () => clearTimeout(splashTimer);
  }, []);

  const requestClean = (selectedIds: string[]) => {
    const targetItems = items.filter(i => selectedIds.includes(i.id));
    setPendingCleanItems(targetItems);
    setIsPreDeleteModalOpen(true);
  };

  const handleConfirmClean = async (createRestorePoint: boolean) => {
    setIsPreDeleteModalOpen(false);
    setCleaning(true);
    const itemIds = pendingCleanItems.map(i => i.id);
    const targetPaths = pendingCleanItems.map(i => i.path);

    try {
      const response = await fetch('http://127.0.0.1:3333/api/clean', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ itemIds, targetPaths, createRestorePoint })
      });
      const data = await response.json();
      if (response.ok && data.success) {
        showToast(`Cleaned ${itemIds.length} items! ${createRestorePoint ? 'Restore Point Created' : 'Soft-deleted to Recycle Bin'}`);
        fetchSystemData();
      } else {
        showToast(`Error: ${data.error || 'Failed to clean items.'}`);
      }
    } catch (e) {
      showToast(`Network / API error: ${(e as Error).message}`);
    } finally {
      setCleaning(false);
      setPendingCleanItems([]);
    }
  };

  const handleOpenFolder = async (folderPath: string) => {
    try {
      await fetch('http://127.0.0.1:3333/api/open-folder', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ folderPath })
      });
    } catch (e) {
      console.warn('API offline - cannot launch Explorer');
    }
  };

  const handleRestoreSnapshot = async (snapshotId: string, customDestinationPath?: string) => {
    try {
      const response = await fetch('http://127.0.0.1:3333/api/snapshots/restore', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ snapshotId, customDestinationPath })
      });
      const data = await response.json();
      if (response.ok && data.success) {
        showToast(`Restored snapshot ${snapshotId}! (${data.restoredCount || 0} items recovered)`);
        fetchSystemData();
      } else {
        showToast(`Error restoring snapshot: ${data.error || 'Failed'}`);
      }
    } catch (e) {
      showToast(`Failed to restore snapshot: ${(e as Error).message}`);
    }
  };

  const handleKillProcess = async (pid: number) => {
    try {
      const res = await fetch('http://127.0.0.1:3333/api/processes/kill', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ pid })
      });
      const data = await res.json();
      if (data.success) {
        showToast(`Terminated process (PID: ${pid})`);
        setProcesses(prev => prev.filter(p => p.pid !== pid));
      } else {
        showToast(`Failed to terminate process ${pid}`);
      }
    } catch (e) {
      showToast(`Error terminating process: ${(e as Error).message}`);
    }
  };

  const showToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 4000);
  };

  return (
    <div style={{ display: 'flex', minHeight: '100vh' }}>
      {/* Toast Notification */}
      {toastMessage && (
        <div style={{
          position: 'fixed',
          bottom: '24px',
          right: '24px',
          background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
          color: '#fff',
          padding: '12px 20px',
          borderRadius: '12px',
          boxShadow: '0 8px 25px rgba(16, 185, 129, 0.4)',
          display: 'flex',
          alignItems: 'center',
          gap: '10px',
          fontWeight: 600,
          zIndex: 3000,
          fontSize: '0.9rem'
        }}>
          <CheckCircle2 size={18} /> {toastMessage}
        </div>
      )}

      {/* LEFT SIDEBAR NAVIGATION */}
      <aside className="glass-card" style={{
        width: '240px',
        minWidth: '240px',
        borderRadius: 0,
        borderRight: '1px solid var(--border-color)',
        borderTop: 'none',
        borderLeft: 'none',
        borderBottom: 'none',
        padding: '24px 16px',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        height: '100vh',
        position: 'sticky',
        top: 0
      }}>
        <div>
          {/* Brand Header */}
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '28px', paddingLeft: '4px' }}>
            <div style={{
              width: '40px',
              height: '40px',
              borderRadius: '12px',
              background: 'linear-gradient(135deg, #00f2fe 0%, #4facfe 100%)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              boxShadow: '0 4px 15px rgba(0, 242, 254, 0.4)'
            }}>
              <ShieldCheck size={24} color="#0b0f19" />
            </div>
            <div>
              <h1 style={{ fontSize: '1.05rem', fontWeight: 800, letterSpacing: '-0.02em', background: 'linear-gradient(90deg, #ffffff, #9ca3af)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>
                AI Clutter Cleaner
              </h1>
              <span style={{ fontSize: '0.68rem', color: '#10b981', fontWeight: 700, letterSpacing: '0.05em' }}>
                v1.0 • 100% FREE FOSS
              </span>
            </div>
          </div>

          {/* Sidebar Menu Items - Concise & Point to Point Naming */}
          <nav style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
            <button
              className={`sidebar-nav-btn ${activeTab === 'DASHBOARD' ? 'active' : ''}`}
              onClick={() => changeTab('DASHBOARD')}
            >
              <LayoutDashboard size={18} color={activeTab === 'DASHBOARD' ? '#ffffff' : '#00f2fe'} />
              <span>Dashboard</span>
            </button>

            <button
              className={`sidebar-nav-btn ${activeTab === 'SAFE_DELETE' ? 'active-green' : ''}`}
              onClick={() => changeTab('SAFE_DELETE')}
            >
              <Sparkles size={18} color={activeTab === 'SAFE_DELETE' ? '#ffffff' : '#34d399'} />
              <span>Safe Delete</span>
            </button>

            <button
              className={`sidebar-nav-btn ${activeTab === 'STORAGE' ? 'active' : ''}`}
              onClick={() => changeTab('STORAGE')}
            >
              <HardDrive size={18} color={activeTab === 'STORAGE' ? '#ffffff' : '#9ca3af'} />
              <span>Drive Footprint</span>
            </button>

            <button
              className={`sidebar-nav-btn ${activeTab === 'SOFTWARE' ? 'active' : ''}`}
              onClick={() => changeTab('SOFTWARE')}
            >
              <Laptop size={18} color={activeTab === 'SOFTWARE' ? '#ffffff' : '#9ca3af'} />
              <span>AI Software</span>
            </button>

            <button
              className={`sidebar-nav-btn ${activeTab === 'AUTOBOTS' ? 'active' : ''}`}
              onClick={() => changeTab('AUTOBOTS')}
            >
              <Bot size={18} color={activeTab === 'AUTOBOTS' ? '#ffffff' : '#c084fc'} />
              <span>Clawbots & Bots</span>
            </button>

            <button
              className={`sidebar-nav-btn ${activeTab === 'HISTORY' ? 'active' : ''}`}
              onClick={() => changeTab('HISTORY')}
            >
              <History size={18} color={activeTab === 'HISTORY' ? '#ffffff' : '#9ca3af'} />
              <span>Restore Points</span>
            </button>

            <button
              className={`sidebar-nav-btn ${activeTab === 'PROCESSES' ? 'active' : ''}`}
              onClick={() => changeTab('PROCESSES')}
            >
              <Cpu size={18} color={activeTab === 'PROCESSES' ? '#ffffff' : '#9ca3af'} />
              <span>Process Inspector</span>
            </button>

            <button
              className={`sidebar-nav-btn ${activeTab === 'MIGRATION' ? 'active' : ''}`}
              onClick={() => changeTab('MIGRATION')}
            >
              <Package size={18} color={activeTab === 'MIGRATION' ? '#ffffff' : '#9ca3af'} />
              <span>PC Migration</span>
            </button>

            <button
              className={`sidebar-nav-btn ${activeTab === 'MEMORY' ? 'active' : ''}`}
              onClick={() => changeTab('MEMORY')}
            >
              <Eye size={18} color={activeTab === 'MEMORY' ? '#ffffff' : '#9ca3af'} />
              <span>Privacy Inspector</span>
            </button>

            <button
              className={`sidebar-nav-btn ${activeTab === 'SETTINGS' ? 'active' : ''}`}
              onClick={() => changeTab('SETTINGS')}
            >
              <Settings size={18} color={activeTab === 'SETTINGS' ? '#ffffff' : '#9ca3af'} />
              <span>Settings</span>
            </button>
          </nav>
        </div>

        {/* BOTTOM LEFT SIDEBAR BRANDING & SAAS DEVELOPMENT CONTACT CTA */}
        <div style={{
          background: 'linear-gradient(135deg, rgba(0, 242, 254, 0.1) 0%, rgba(157, 78, 221, 0.1) 100%)',
          padding: '12px',
          borderRadius: '12px',
          border: '1px solid rgba(0, 242, 254, 0.3)',
          display: 'flex',
          flexDirection: 'column',
          gap: '6px',
          marginTop: 'auto'
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', color: '#00f2fe', fontSize: '0.8rem', fontWeight: 800 }}>
            <Code2 size={16} /> Dice Codes
          </div>
          <p style={{ fontSize: '0.72rem', color: '#9ca3af', lineHeight: '1.3' }}>
            Need custom AI software or web apps?
          </p>
          <a
            href="https://dicecodes.com/"
            target="_blank"
            rel="noopener noreferrer"
            style={{
              fontSize: '0.74rem',
              color: '#ffffff',
              background: 'linear-gradient(135deg, #00c6ff 0%, #0072ff 100%)',
              padding: '6px 10px',
              borderRadius: '8px',
              textDecoration: 'none',
              fontWeight: 700,
              display: 'inline-flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: '4px',
              boxShadow: '0 2px 10px rgba(0, 198, 255, 0.3)'
            }}
          >
            Visit DiceCodes.com ↗
          </a>
        </div>
      </aside>

      {/* MAIN CONTENT WORKSPACE */}
      <main style={{ flex: 1, padding: '32px', overflowY: 'auto', maxHeight: '100vh' }}>
        {activeTab === 'DASHBOARD' && (
          <MainDashboardView
            metrics={metrics}
            items={items}
            loading={loading}
            onRefresh={fetchSystemData}
            onCleanSelected={requestClean}
            onExportVault={() => changeTab('MIGRATION')}
            onOpenFolder={handleOpenFolder}
            onNavigateTab={(tab) => changeTab(tab)}
          />
        )}

        {activeTab === 'SAFE_DELETE' && (
          <SafeDeleteSection
            items={items}
            onCleanSelected={requestClean}
            onOpenFolder={handleOpenFolder}
          />
        )}

        {activeTab === 'STORAGE' && (
          <TargetListTable
            items={items}
            onCleanSelected={requestClean}
            onOpenFolder={handleOpenFolder}
          />
        )}

        {activeTab === 'SOFTWARE' && (
          <AISoftwareTab
            processes={processes}
            onKillProcess={handleKillProcess}
          />
        )}

        {activeTab === 'AUTOBOTS' && (
          <AutoBotsTab
            processes={processes}
            onKillBot={handleKillProcess}
          />
        )}

        {activeTab === 'HISTORY' && (
          <HistoryTab
            snapshots={snapshots}
            onRestore={handleRestoreSnapshot}
            onOpenFolder={handleOpenFolder}
          />
        )}

        {activeTab === 'PROCESSES' && (
          <ProcessInspector
            processes={processes}
            onKillProcess={handleKillProcess}
          />
        )}

        {activeTab === 'MIGRATION' && (
          <MigrationWizard
            onOpenFolder={handleOpenFolder}
          />
        )}

        {activeTab === 'MEMORY' && (
          <MemoryInspector />
        )}

        {activeTab === 'SETTINGS' && (
          <SettingsTab updateInfo={updateInfo} onCheckUpdate={checkGitHubUpdate} />
        )}
      </main>

      {/* PRE-DELETION SAFETY CHECKLIST MODAL */}
      <PreDeleteModal
        isOpen={isPreDeleteModalOpen}
        itemsToClean={pendingCleanItems}
        onConfirm={handleConfirmClean}
        onCancel={() => setIsPreDeleteModalOpen(false)}
      />
    </div>
  );
};

export default App;

